tkj = "nova"
print (tkj)
var1 = 20
var2 = 30
var3 = var1+var2
print (var1+var2)
print (type(var1+var2))

var1 = 10
var2 = 90
aku = var1*var2
print (var1*var2)

var1 = 20
var2 = 7
var3 = var1 / var2
print (var1 / var2)

name = "nova"
city = "Jakarta"
print ("Hello {0}, from {1}" .format (name,city))

print ("hello {}, from {}".format (name,city))

list = ["tkj",1,2,111.1]
print ("list [2]")









