#soal 1#
print ("Hello World Python")

#soal 2#
var1 = 10
var2 = 20
var3 = var1 + var2 

print (var3)
var1 = 20
var2 = 5
var3 = var1 - var2

print (var3)
print (5+10)
print (20*5)
print (20 // 5)
print (10 + 15)

#soal 3#
varA = 10
varB = 5
varC = 10 // 5
print (varC)

print (type(10 // 5))
print (type(varA // varB))

print (type(10 / 5))

#soal 4#
usia = "28 tahun"
kata = "usiaku:"

print ("{} {}". format(kata,usia))



